### PR TITLE
make compatible with ansible language package

### PR DESCRIPTION
**Pull request by smiller171**

### CODE REVIEW

**Comment by h-hirokawa** [comment]
Thank you for PR!

**Comment by smiller171** [comment]
@h-hirokawa I think I may have done something wrong, as the latest version isn't autocompleting with the ansible language package. I think my syntax may be wrong as it is slightly different in #8

**Comment by smiller171** [comment]
@h-hirokawa I've confirmed locally that my syntax was wrong but it is correct in #8 

I'd advise backing out this PR and replacing it with #8. Alternatively I can issue a new PR with the fix.

**Comment by h-hirokawa** [comment]
Thanks for reporting. I mistook the PRs :dizzy_face:

**Pull request merged**
