### PR TITLE
ansible 2.10.* DocCLI.find_plugins fix

### LINKED ISSUE #50: TypeError: on line 44, in parse_ansible.py after upgrading ansible
Hi guys, 

love this package on atom, saves me so mucht time. But after upgrading I am running into this error. Any ideas whats up?

`Command failed: "/.../.pyenv/shims/python" "/.../.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
Traceback (most recent call last):
  File "/.../.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 98, in <module>
    print(main())
  File "/.../.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 56, in main
    for module in get_module_list():
  File "/.../.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 44, in get_module_list
    founds = doc_cli.find_plugins(path, 'module')
TypeError: find_plugins() missing 1 required positional argument: 'ptype'`

### LINKED ISSUE #51: autocomplete fails to load.
TypeError: find_plugins() missing 1 required positional argument: 'ptype'

ArchLinux

### PR DESCRIPTION
**Pull request by ebenezar-mccoy**

### CODE REVIEW

**Comment by dnorthup-ums** [comment]
@ebenezar-mccoy TY, I'll have a look at this.

**Comment by dnorthup-ums** [comment]
I'm willing to accept this as an interim fix. We still have similar fixes around from previous versions that weren't well labeled (the author was just trying to keep it working) but fixed the problem at the time yet are no longer needed and make the code harder to follow today.
In the meantime, I'll see what, if anything, I need to do to get the CI run to finish.

**Comment by dnorthup-ums** [comment]
The CI run passed, but it isn't updating here for some reason. I'll probably just merge this in by hand.

@ebenezar-mccoy FYI, I'll be rebasing and discarding the extra merge commit if I do it by hand.

**Comment by brzoza-daath** [comment]
Hi @dnorthup-ums any update on this ? Could you tell when we can expect this will be merged ?

**Comment by dnorthup-ums** [comment]
@brzoza-daath & @ebenezar-mccoy Because I don't own this repo I can't force-override the merge when the CI checks don't return status. I'm attempting to get the checks to run in #56 so I can do the merge, increment the release, etc.

**Comment by dnorthup-ums** [comment]
Changes merged in #56

**Pull request closed without merging**
