### PR TITLE
fixing ansible 2.9

### PR DESCRIPTION
**Pull request by ebenezar-mccoy**

### CODE REVIEW

**Comment by dnorthup-ums** [comment]
This is very close to what I first tried. It passed the automated tests yet fails when tried in a live atom editor instance.

**Comment by slitsevych** [comment]
Thank you, @ebenezar-mccoy , for this simple and elegant fix: I have manually implemented the line changes represented in this pull request and it helped me to bring the package's functionality back. 

ansible 2.9.0
python 3.6.9
atom 1.41.0

**Comment by brzoza-daath** [comment]
Thanks @ebenezar-mccoy it worked for me as well.
Here is more automated way to apply this patch

`wget https://github.com/h-hirokawa/atom-autocomplete-ansible/pull/45/commits/e5781c883a94f3f16f14c50d31bbcf4f2933d6d2.patch`
`cd ~/.atom/packages/autocomplete-ansible`
`patch -p1 -i ~/Downloads/patches/e5781c883a94f3f16f14c50d31bbcf4f2933d6d2.patch`
`patching file libs/parse_ansible.py`
`patching file libs/provider.js`

**Comment by dnorthup-ums** [comment]
After restarting atom twice I managed to verify this fix. (Still not sure why I had to do that.) I'm also still not sure why the first time I tried basically the same thing it didn't work, but this patch is here so use it.

**Comment by dnorthup-ums** [comment]
The UI here hasn't updated yet, but the Travis CI checks on this pass.

**Pull request merged**
